# Generated by Django 2.0.7 on 2018-09-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('multicast', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_error_raise_counter', models.PositiveIntegerField()),
                ('udp_error_raise_counter', models.PositiveIntegerField()),
                ('udp_lost_packages_counter', models.PositiveIntegerField()),
            ],
        ),
    ]
