# Generated by Django 2.0.7 on 2018-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='test_counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
