# Generated by Django 2.0.7 on 2018-09-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0003_remove_error_test_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error',
        ),
    ]
