# Generated by Django 2.0.7 on 2018-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0004_delete_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_error_raise_counter', models.PositiveIntegerField()),
                ('udp_error_raise_counter', models.PositiveIntegerField()),
                ('udp_lost_packages_counter', models.PositiveIntegerField()),
            ],
        ),
    ]
