# Generated by Django 2.0.7 on 2018-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0005_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='error_time',
            field=models.DateTimeField(null=True),
        ),
    ]
