# Generated by Django 2.0.7 on 2018-09-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0006_error_error_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error',
        ),
    ]
