# Generated by Django 2.0.7 on 2018-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0008_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrate_time', models.DateTimeField(null=True)),
                ('channel_id', models.PositiveIntegerField()),
                ('bitrate_kbs', models.PositiveIntegerField()),
            ],
        ),
    ]
