# Generated by Django 2.0.7 on 2018-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0009_bitrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
