# Generated by Django 2.0.7 on 2018-09-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0012_auto_20180905_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='channel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='twos_rest_api.Channel'),
        ),
    ]
