# Generated by Django 2.0.7 on 2018-09-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0013_auto_20180907_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='channel_id',
            new_name='channel',
        ),
    ]
