# Generated by Django 2.0.7 on 2018-09-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0014_auto_20180907_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'ordering': ['cc_error_raise_counter']},
        ),
        migrations.AlterField(
            model_name='error',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='errors', to='twos_rest_api.Channel'),
        ),
        migrations.AlterUniqueTogether(
            name='error',
            unique_together={('channel', 'cc_error_raise_counter')},
        ),
    ]
