# Generated by Django 2.0.7 on 2018-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twos_rest_api', '0015_auto_20180910_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='error',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='error',
            unique_together={('channel', 'id')},
        ),
    ]
